version: "3"
services:
  application:
    build: .
    image: gamja123/boards
    container_name: was-application
    ports:
      - "8080:8080"
    environment:
      - JASYPT_SECRETE_KEY=HelloWorld
    restart: on-failure
