spring:
  profiles:
    active: prod  # 개발 환경에 따라 local 또는 prod로 변경

---
spring:
  datasource:
    url: ENC(kG2t+OzSazC0wd3j4ZsfrlfIS/SLKiz1ZUmrG7D9oIbEdF3qrmVBw5n8YXTxVGtZ)
    username: ENC(yTakvbGBJAuwXNWjLb7eVg==)
    password: ENC(9GbAxtndVbKhOnZR1sOUuw==)
  jpa:
    properties:
      hibernate:
        format_sql: true
  config:
    activate:
      on-profile: local
logging.level:
  org.hibernate.SQL: debug
JWT_SECRET_KEY: key
---
spring:
  datasource:
    url: ENC(ByFEtmhhZcaelaV7PchRITLuEpprcXk+URWdTL1oSaGwiqBmmaviu6G5whE1axzPmcIIRIpnIk/b+KC0uNSaBgbxwixg6zGYOxWhUEdblPLa0Y7BetNikg==)
    username: ENC(T9P4O/YNFhAcqkAxejjBIA==)
    password: ENC(LdyBvCTtIkFPN3p7xcO3EK7oaibYTT76)
  jpa:
    properties:
      hibernate:
        format_sql: true
  config:
    activate:
      on-profile: prod
logging.level:
  org.hibernate.SQL: debug
JWT_SECRET_KEY: key
#  org.hibernate.type: trace
