jasypt:
  secrete-key: ${JASYPT_SECRETE_KEY}

spring:
  datasource:
    url: ENC(EmeVnqtrE5v/z62gMr3e4dSgo/MC+l+vtxUvgAslWzHFXcpcjfq9+HjFviknx28QFwTMMFB3qA8A6wQhMy2HIL8ZaUkznGsZM3hoduguZ2Co/nmW+fVA/A==)
    username: ENC(Dit6IbTLxXkWioBnMyzXZg==)
    password: ENC(ZDsXnXm+P/4m0UfT/E0XEb9YRLIk2u3y)
  jpa:
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug

JWT_SECRET_KEY: key
