jasypt:
  secrete-key: ${JASYPT_SECRETE_KEY}

spring:
  datasource:
    url: ENC(1GvVPrtIiBKK/IycsuvtpcMft/CYh5sYsPnYffz00u7oatcI4RRP2HAMsu34uZSp)
    username: ENC(MNFOLjPUWV0YTn6kM/tvBQ==)
    password: ENC(YpxgkiimilVr84gat/kiVQ==)
  jpa:
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug

JWT_SECRET_KEY: key
