#spring:
#  profiles:
#    active: local
#---
jasypt:
  secrete-key: ${JASYPT_SECRETE_KEY}

spring:
  datasource:
    url: ENC(1GvVPrtIiBKK/IycsuvtpcMft/CYh5sYsPnYffz00u7oatcI4RRP2HAMsu34uZSp)
    username: ENC(MNFOLjPUWV0YTn6kM/tvBQ==)
    password: ENC(YpxgkiimilVr84gat/kiVQ==)
  jpa:
    properties:
      hibernate:
        format_sql: true
  config:
    activate:
      on-profile: local
logging:
  level:
    org.hibernate.SQL: debug

JWT_SECRET_KEY: key
#---
#jasypt:
#  secrete-key: ${JASYPT_SECRETE_KEY}
#
#spring:
#  datasource:
#    url: ENC(aWZcT/yWiMQlGshksZnx/SibjHIjogK5csUD3FxWJRFXGgiQEDuZtPkcRxL+91wCCySqr8VG4kll/v3ZIA10o5cwFhGqs0XCtd+S7wjXe47sDvrgU6EjvA==)
#    username: ENC(fMeARi67V2bjwVMTREy+Ww==)
#    password: ENC(/MGRMQrvSFaaWzCR4hQJhzhY/g9zCglH)
#  jpa:
#    properties:
#      hibernate:
#        format_sql: true
#  config:
#    activate:
#      on-profile: prod
#logging:
#  level:
#    org.hibernate.SQL: debug
#
#JWT_SECRET_KEY: key
